from themer import DefaultTheme

class Theme(DefaultTheme):
    # These colors were chosen specifically because they're hard to miss.
    # Using this theme on an actual device is not advised
    # The default theme was generated by removing all the lines below and adding `pass` instead.
    BLE_COLOR = 0xfb80
    SCROLL_INDICATOR_COLOR = 0xf800
    BATTERY_COLOR = 0x07ff
    SMALL_CLOCK_COLOR = 0x599f
    NOTIFICATION_COLOR = 0x8fe0
    ACCENT_MID = 0xf800
    ACCENT_LO = 0x001f
    ACCENT_HI = 0x07e0
    SLIDER_DEFAULT_COLOR = 0x7777
