from themer import DefaultTheme


class Theme(DefaultTheme):
    # These colors were chosen specifically because they're hard to miss.
    # Using this theme on an actual device is not advised
    # The default theme was generated by removing all the lines below and adding `pass` instead.
    BLE_COLOR = 0xFB80
    SCROLL_INDICATOR_COLOR = 0xF800
    BATTERY_COLOR = 0x07FF
    SMALL_CLOCK_COLOR = 0x599F
    NOTIFICATION_COLOR = 0x8FE0
    BRIGHT = 0xFFFF
    MID = 0xFF00
    UI = 0x39FF
    SPOT1 = 0x00FF
    SPOT2 = 0x44D0
    CONTRAST = 7
