from themer import DefaultTheme

class Theme(DefaultTheme):
    # These colors were chosen specifically because they're hard to miss.
    # Using this theme on an actual device is not advised
    # The default theme was generated by removing all the lines below and adding `pass` instead.
    BLE_COLOR = 0xfb80
    SCROLL_INDICATOR_COLOR = 0xf800
    BATTERY_COLOR = 0x07ff
    SMALL_CLOCK_COLOR = 0x599f
    NOTIFICATION_COLOR = 0x8fe0
    BRIGHT = 0xffff
    MID = 0xff00
    UI = 0x39ff
    SPOT1 = 0x00ff
    SPOT2 = 0x44d0
    CONTRAST = 7
